# -*- coding: utf-8 -*-
"""RAG_practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/195E3BMrR0vaX8EeC7d6-KBKPk4rjbaGD
"""



!pip -q install python-docx sentence-transformers faiss-cpu numpy

from google.colab import files
uploaded = files.upload()

docx_path = next(iter(uploaded.keys()))
print("Loaded:", docx_path)

from docx import Document
import re

def read_docx_blocks(path):
    doc = Document(path)
    lines = []
    for p in doc.paragraphs:
        t = p.text.strip()
        if t:
            lines.append(t)
    return lines

def is_heading(line: str) -> bool:
    # Heuristic: ALL CAPS or ends with ":" or looks like a title line
    if len(line) <= 70 and line.isupper():
        return True
    if len(line) <= 70 and line.endswith(":"):
        return True
    # Example: "DNA REPLICATION", "MECHANISM OF DNA REPLICATION" etc.
    if len(line) <= 70 and re.match(r"^[A-Z0-9 ,()\-]+$", line) and sum(c.isalpha() for c in line) > 6:
        return True
    return False

def group_by_heading(lines):
    blocks = []
    current_heading = "UNTITLED"
    current_text = []

    for line in lines:
        if is_heading(line):
            if current_text:
                blocks.append({"heading": current_heading, "text": "\n".join(current_text).strip()})
            current_heading = line.strip(":").strip()
            current_text = []
        else:
            current_text.append(line)

    if current_text:
        blocks.append({"heading": current_heading, "text": "\n".join(current_text).strip()})

    return blocks

lines = read_docx_blocks(docx_path)
blocks = group_by_heading(lines)

print("Total heading-blocks:", len(blocks))
print("Example block heading:", blocks[0]["heading"])
print("Example block preview:\n", blocks[0]["text"][:400])

import numpy as np
import faiss
from sentence_transformers import SentenceTransformer

EMBED_MODEL = "sentence-transformers/all-MiniLM-L6-v2"  # fast baseline
# If you later want stronger retrieval, try:
# EMBED_MODEL = "BAAI/bge-base-en-v1.5"

embedder = SentenceTransformer(EMBED_MODEL)

# Create normalized embeddings (so cosine similarity == inner product)
emb = embedder.encode(chunks, normalize_embeddings=True, show_progress_bar=True)
emb = np.array(emb, dtype=np.float32)

dim = emb.shape[1]
index = faiss.IndexFlatIP(dim)  # Inner Product on normalized vectors = cosine similarity
index.add(emb)

print("FAISS index ready. Vectors:", index.ntotal, "Dim:", dim)

def retrieve(query, k=5):
    q_emb = embedder.encode([query], normalize_embeddings=True)
    q_emb = np.array(q_emb, dtype=np.float32)

    scores, ids = index.search(q_emb, k)
    results = []
    for rank, idx in enumerate(ids[0]):
        results.append({
            "rank": rank + 1,
            "score": float(scores[0][rank]),
            "heading": metas[idx]["heading"],
            "chunk_id": metas[idx]["chunk_id"],
            "text": chunks[idx]
        })
    return results

# Quick test (uses topics that exist in your notes like DNA replication + enzymes) :contentReference[oaicite:2]{index=2}
results = retrieve("Explain initiation and elongation in DNA replication", k=5)
for r in results:
    print(f"\n#{r['rank']} | score={r['score']:.3f} | heading={r['heading']} | chunk={r['chunk_id']}")
    print(r["text"][:350], "...")

def rag_answer_light(query, k=5):
    hits = retrieve(query, k=k)

    context = "\n\n".join(
        [f"[{h['heading']} | chunk {h['chunk_id']} | score {h['score']:.3f}]\n{h['text']}"
         for h in hits]
    )

    # Lightweight “answer” (no LLM): just returns curated context + a short heuristic summary
    summary_lines = [
        f"- From **{hits[0]['heading']}**: {hits[0]['text'][:180].strip()}...",
    ]
    if len(hits) > 1:
        summary_lines.append(f"- Also relevant: **{hits[1]['heading']}** (score {hits[1]['score']:.3f}).")

    return {
        "query": query,
        "top_evidence": hits,
        "summary": "\n".join(summary_lines),
        "context": context
    }

out = rag_answer_light("What is the role of helicase, primase, and ligase in DNA replication?", k=5)
print(out["summary"])
print("\n--- Evidence Context ---\n")
print(out["context"][:1500], "...")

!pip -q install transformers accelerate